### ISSUE TITLE
Event-driven automations?

### ISSUE THREAD

**Issue by walking-octopus** [ddellacosta/automation-service#22]
- As far as I can see, you are using pooling with setup() and update() functions in the scripts.
- This is rather inefficient on the CPU.
- Perhaps some kind of event-based way to trigger the functions can be made?
- For example, Pyscript does it like this:
 ```python
@state_trigger("security.rear_motion == '1' or security.side_motion == '1'")
@time_active("range(sunset - 20min, sunrise + 20min)")
def motion_light_rear():
    """Turn on rear light for 5 minutes when there is motion and it's dark"""
    task.unique("motion_light_rear")
    log.info(f"triggered; turning on the light")
    if light.outside_rear != "on":
        light.turn_on(entity_id="light.outside_rear", brightness=255)
    task.sleep(300)
    light.turn_off(entity_id="light.outside_rear")
```

**Comment by ddellacosta** [comment]
Hey sorry, I just finally noticed you posted, just haven't been paying as much attention to this lately. I appreciate you commenting.

So there are definitely some improvements I can make to the efficiency of automations I'm sure, but I don't understand this statement--can you explain more?

> As far as I can see, you are using pooling with setup() and update() functions in the scripts.

Where are you seeing the pooling in particular--are you talking about a thread pool, or something else?

The way these lua automations are supposed to work is that they shouldn't be doing anything other than waiting on a STM channel inside of a `loop` function if there is some event they are dependent on, e.g. [here](https://github.com/ddellacosta/automation-service/blob/07f251785d87ebd8eef41073dce24e929eb64244/lua-automations/frontDoor.lua#L15). You can see the implementation for this in the [LuaScript](https://github.com/ddellacosta/automation-service/blob/07f251785d87ebd8eef41073dce24e929eb64244/src/Service/Automations/LuaScript.hs#L379-L401) code. To the best of my knowledge a blocked thread shouldn't incur any CPU cost so should be "maximally" efficient in that sense, although there is an ongoing memory cost of course. So this is basically an event-driven approach.

Your comment reminded me that I really need some better documentation :grimacing:

**Comment by ddellacosta** [comment]
Gonna close this as it seems like that answered your concerns, but let me know if there's anything else.
